2017-06-27 08:08:22.151 +08:00 [Information] "Host","20022","e:\pic",IPv6,Unknown------------------------------------
2017-06-27 08:08:23.685 +08:00 [Fatal] Unable to start Kestrel.
System.AggregateException: One or more errors occurred. (Error -4090 EADDRNOTAVAIL address not available) ---> Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvException: Error -4090 EADDRNOTAVAIL address not available
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.ThrowError(Int32 statusCode)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.tcp_bind(UvTcpHandle handle, SockAddr& addr, Int32 flags)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvTcpHandle.Bind(ServerAddress address)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.TcpListenerPrimary.CreateListenSocket()
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Listener.<StartAsync>b__8_0(Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.ListenerPrimary.<StartAsync>d__12.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.KestrelEngine.CreateServer(ServerAddress address)
   at Microsoft.AspNetCore.Server.Kestrel.KestrelServer.Start[TContext](IHttpApplication`1 application)
---> (Inner Exception #0) Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvException: Error -4090 EADDRNOTAVAIL address not available
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.ThrowError(Int32 statusCode)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.tcp_bind(UvTcpHandle handle, SockAddr& addr, Int32 flags)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvTcpHandle.Bind(ServerAddress address)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.TcpListenerPrimary.CreateListenSocket()
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Listener.<StartAsync>b__8_0(Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.ListenerPrimary.<StartAsync>d__12.MoveNext()<---

2017-06-27 08:13:20.072 +08:00 [Information] "Host","20022","e:\pic",IPv6,Unknown------------------------------------
2017-06-27 08:13:20.828 +08:00 [Fatal] Unable to start Kestrel.
System.AggregateException: One or more errors occurred. (Error -4090 EADDRNOTAVAIL address not available) ---> Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvException: Error -4090 EADDRNOTAVAIL address not available
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.ThrowError(Int32 statusCode)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.tcp_bind(UvTcpHandle handle, SockAddr& addr, Int32 flags)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvTcpHandle.Bind(ServerAddress address)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.TcpListenerPrimary.CreateListenSocket()
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Listener.<StartAsync>b__8_0(Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.ListenerPrimary.<StartAsync>d__12.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.KestrelEngine.CreateServer(ServerAddress address)
   at Microsoft.AspNetCore.Server.Kestrel.KestrelServer.Start[TContext](IHttpApplication`1 application)
---> (Inner Exception #0) Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvException: Error -4090 EADDRNOTAVAIL address not available
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.ThrowError(Int32 statusCode)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.tcp_bind(UvTcpHandle handle, SockAddr& addr, Int32 flags)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvTcpHandle.Bind(ServerAddress address)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.TcpListenerPrimary.CreateListenSocket()
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Listener.<StartAsync>b__8_0(Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.ListenerPrimary.<StartAsync>d__12.MoveNext()<---

2017-06-27 08:26:27.673 +08:00 [Information] "Host","20022","e:\pic",IPv6,Unknown------------------------------------
2017-06-27 08:26:28.521 +08:00 [Fatal] Unable to start Kestrel.
System.AggregateException: One or more errors occurred. (Error -4090 EADDRNOTAVAIL address not available) ---> Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvException: Error -4090 EADDRNOTAVAIL address not available
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.ThrowError(Int32 statusCode)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.tcp_bind(UvTcpHandle handle, SockAddr& addr, Int32 flags)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvTcpHandle.Bind(ServerAddress address)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.TcpListenerPrimary.CreateListenSocket()
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Listener.<StartAsync>b__8_0(Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.ListenerPrimary.<StartAsync>d__12.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.KestrelEngine.CreateServer(ServerAddress address)
   at Microsoft.AspNetCore.Server.Kestrel.KestrelServer.Start[TContext](IHttpApplication`1 application)
---> (Inner Exception #0) Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvException: Error -4090 EADDRNOTAVAIL address not available
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.ThrowError(Int32 statusCode)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.tcp_bind(UvTcpHandle handle, SockAddr& addr, Int32 flags)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvTcpHandle.Bind(ServerAddress address)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.TcpListenerPrimary.CreateListenSocket()
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Listener.<StartAsync>b__8_0(Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.ListenerPrimary.<StartAsync>d__12.MoveNext()<---

2017-06-27 08:26:39.941 +08:00 [Information] "Host","20022","e:\pic",IPv6,Unknown------------------------------------
2017-06-27 08:26:42.066 +08:00 [Information] Request starting HTTP/1.1 GET http://localhost:5000/  
2017-06-27 08:26:42.751 +08:00 [Information] Request finished in 732.8208ms 404 
2017-06-27 08:26:42.797 +08:00 [Information] Request starting HTTP/1.1 GET http://localhost:5000/  
2017-06-27 08:26:42.806 +08:00 [Information] Request finished in 8.8322ms 404 
2017-06-27 08:26:42.884 +08:00 [Information] Request starting HTTP/1.1 GET http://localhost:5000/favicon.ico  
2017-06-27 08:26:42.909 +08:00 [Information] Request finished in 25.1538ms 404 
2017-06-27 08:27:03.499 +08:00 [Information] Request starting HTTP/1.1 POST http://localhost:5000/loginandquery application/json 72
2017-06-27 08:27:04.042 +08:00 [Information] Executing action method "study.Controllers.InspectController.LoginAndQuery (study)" with arguments (["study.LoginAndQueryRequest"]) - ModelState is Valid
2017-06-27 08:27:04.145 +08:00 [Information] LoginAndQuery,input="{\"Identity\":\"370686199102070710\",\"Name\":null,\"DrivingLicenseType\":0,\"Phone\":null,\"Wechat\":null}",from "::1"
2017-06-27 08:27:04.146 +08:00 [Information] LoginAndQuery inputRequest="{\"Identity\":\"370686199102070710\",\"Name\":null,\"DrivingLicenseType\":0,\"Phone\":null,\"Wechat\":null}"
2017-06-27 08:27:05.976 +08:00 [Information] Executing ObjectResult, writing value "Microsoft.AspNetCore.Mvc.ControllerContext".
2017-06-27 08:27:06.057 +08:00 [Information] Executed action "study.Controllers.InspectController.LoginAndQuery (study)" in 2487.7603ms
2017-06-27 08:27:06.063 +08:00 [Information] Request finished in 2563.957ms 200 application/json; charset=utf-8
2017-06-27 08:32:04.022 +08:00 [Information] "Host","20022","e:\pic",IPv6,Unknown------------------------------------
2017-06-27 08:32:04.731 +08:00 [Fatal] Unable to start Kestrel.
System.AggregateException: One or more errors occurred. (Error -4090 EADDRNOTAVAIL address not available) ---> Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvException: Error -4090 EADDRNOTAVAIL address not available
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.ThrowError(Int32 statusCode)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.tcp_bind(UvTcpHandle handle, SockAddr& addr, Int32 flags)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvTcpHandle.Bind(ServerAddress address)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.TcpListenerPrimary.CreateListenSocket()
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Listener.<StartAsync>b__8_0(Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.ListenerPrimary.<StartAsync>d__12.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.KestrelEngine.CreateServer(ServerAddress address)
   at Microsoft.AspNetCore.Server.Kestrel.KestrelServer.Start[TContext](IHttpApplication`1 application)
---> (Inner Exception #0) Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvException: Error -4090 EADDRNOTAVAIL address not available
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.ThrowError(Int32 statusCode)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.tcp_bind(UvTcpHandle handle, SockAddr& addr, Int32 flags)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvTcpHandle.Bind(ServerAddress address)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.TcpListenerPrimary.CreateListenSocket()
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Listener.<StartAsync>b__8_0(Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.ListenerPrimary.<StartAsync>d__12.MoveNext()<---

2017-06-27 08:40:31.842 +08:00 [Information] "Host","20022","e:\pic",IPv6,Unknown------------------------------------
2017-06-27 08:40:33.677 +08:00 [Information] Request starting HTTP/1.1 GET http://localhost:5000/  
2017-06-27 08:40:34.142 +08:00 [Information] Request finished in 495.9488ms 404 
2017-06-27 08:40:34.169 +08:00 [Information] Request starting HTTP/1.1 GET http://localhost:5000/  
2017-06-27 08:40:34.176 +08:00 [Information] Request finished in 6.0638ms 404 
2017-06-27 09:00:26.675 +08:00 [Information] "Host","20022","e:\pic","e:\piclog","e:\pic"------------------------------------
2017-06-27 09:00:28.620 +08:00 [Information] Request starting HTTP/1.1 GET http://localhost:5000/  
2017-06-27 09:00:29.057 +08:00 [Information] Request finished in 464.1049ms 404 
2017-06-27 09:00:29.108 +08:00 [Information] Request starting HTTP/1.1 GET http://localhost:5000/  
2017-06-27 09:00:29.112 +08:00 [Information] Request finished in 3.4963ms 404 
2017-06-27 09:10:31.220 +08:00 [Information] "Host","20022","e:\pic","e:\piclog","e:\pic"------------------------------------
2017-06-27 09:10:33.103 +08:00 [Information] Request starting HTTP/1.1 GET http://localhost:5000/  
2017-06-27 09:10:33.512 +08:00 [Information] Request finished in 436.1124ms 404 
2017-06-27 09:10:33.548 +08:00 [Information] Request starting HTTP/1.1 GET http://localhost:5000/  
2017-06-27 09:10:33.554 +08:00 [Information] Request finished in 6.6105ms 404 
2017-06-27 09:20:10.615 +08:00 [Information] "Host","20022","e:\picsig","e:\piclog","e:\pic"------------------------------------
2017-06-27 09:20:12.484 +08:00 [Information] Request starting HTTP/1.1 GET http://localhost:5000/  
2017-06-27 09:20:12.918 +08:00 [Information] Request finished in 461.8686ms 404 
2017-06-27 09:20:12.944 +08:00 [Information] Request starting HTTP/1.1 GET http://localhost:5000/  
2017-06-27 09:20:12.948 +08:00 [Information] Request finished in 3.4316ms 404 
2017-06-27 14:14:33.390 +08:00 [Information] "Host","20022","e:\picsig","e:\piclog","e:\pic"------------------------------------
2017-06-27 14:14:35.332 +08:00 [Information] Request starting HTTP/1.1 GET http://localhost:5000/  
2017-06-27 14:14:35.746 +08:00 [Information] Request finished in 426.7385ms 404 
2017-06-27 14:14:35.785 +08:00 [Information] Request starting HTTP/1.1 GET http://localhost:5000/  
2017-06-27 14:14:35.791 +08:00 [Information] Request finished in 5.1065ms 404 
2017-06-27 14:14:52.576 +08:00 [Information] "Host","20022","e:\picsig","e:\piclog","e:\pic"------------------------------------
2017-06-27 14:14:53.459 +08:00 [Fatal] Unable to start Kestrel.
System.AggregateException: One or more errors occurred. (Error -4090 EADDRNOTAVAIL address not available) ---> Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvException: Error -4090 EADDRNOTAVAIL address not available
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.ThrowError(Int32 statusCode)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.tcp_bind(UvTcpHandle handle, SockAddr& addr, Int32 flags)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvTcpHandle.Bind(ServerAddress address)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.TcpListenerPrimary.CreateListenSocket()
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Listener.<StartAsync>b__8_0(Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.ListenerPrimary.<StartAsync>d__12.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.KestrelEngine.CreateServer(ServerAddress address)
   at Microsoft.AspNetCore.Server.Kestrel.KestrelServer.Start[TContext](IHttpApplication`1 application)
---> (Inner Exception #0) Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvException: Error -4090 EADDRNOTAVAIL address not available
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.ThrowError(Int32 statusCode)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.tcp_bind(UvTcpHandle handle, SockAddr& addr, Int32 flags)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvTcpHandle.Bind(ServerAddress address)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.TcpListenerPrimary.CreateListenSocket()
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Listener.<StartAsync>b__8_0(Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.ListenerPrimary.<StartAsync>d__12.MoveNext()<---

2017-06-27 16:28:36.696 +08:00 [Information] "Host","20022","e:\picsig","e:\piclog","e:\pic"------------------------------------
2017-06-27 16:28:38.730 +08:00 [Information] Request starting HTTP/1.1 GET http://localhost:5000/  
2017-06-27 16:28:39.202 +08:00 [Information] Request finished in 469.1847ms 404 
2017-06-27 16:28:39.228 +08:00 [Information] Request starting HTTP/1.1 GET http://localhost:5000/  
2017-06-27 16:28:39.233 +08:00 [Information] Request finished in 4.8203ms 404 
2017-06-27 16:28:39.261 +08:00 [Information] Request starting HTTP/1.1 GET http://localhost:5000/favicon.ico  
2017-06-27 16:28:39.272 +08:00 [Information] Request finished in 11.2702ms 404 
2017-06-27 16:28:55.198 +08:00 [Information] "Host","20022","e:\picsig","e:\piclog","e:\pic"------------------------------------
2017-06-27 16:28:56.109 +08:00 [Fatal] Unable to start Kestrel.
System.AggregateException: One or more errors occurred. (Error -4090 EADDRNOTAVAIL address not available) ---> Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvException: Error -4090 EADDRNOTAVAIL address not available
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.ThrowError(Int32 statusCode)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.tcp_bind(UvTcpHandle handle, SockAddr& addr, Int32 flags)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvTcpHandle.Bind(ServerAddress address)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.TcpListenerPrimary.CreateListenSocket()
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Listener.<StartAsync>b__8_0(Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.ListenerPrimary.<StartAsync>d__12.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.KestrelEngine.CreateServer(ServerAddress address)
   at Microsoft.AspNetCore.Server.Kestrel.KestrelServer.Start[TContext](IHttpApplication`1 application)
---> (Inner Exception #0) Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvException: Error -4090 EADDRNOTAVAIL address not available
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.ThrowError(Int32 statusCode)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.tcp_bind(UvTcpHandle handle, SockAddr& addr, Int32 flags)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvTcpHandle.Bind(ServerAddress address)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.TcpListenerPrimary.CreateListenSocket()
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Listener.<StartAsync>b__8_0(Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.ListenerPrimary.<StartAsync>d__12.MoveNext()<---

2017-06-27 16:38:18.836 +08:00 [Information] "Host","20022","e:\picsig","e:\piclog","e:\pic"------------------------------------
2017-06-27 16:38:19.660 +08:00 [Fatal] Unable to start Kestrel.
System.AggregateException: One or more errors occurred. (Error -4090 EADDRNOTAVAIL address not available) ---> Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvException: Error -4090 EADDRNOTAVAIL address not available
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.ThrowError(Int32 statusCode)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.tcp_bind(UvTcpHandle handle, SockAddr& addr, Int32 flags)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvTcpHandle.Bind(ServerAddress address)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.TcpListenerPrimary.CreateListenSocket()
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Listener.<StartAsync>b__8_0(Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.ListenerPrimary.<StartAsync>d__12.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.KestrelEngine.CreateServer(ServerAddress address)
   at Microsoft.AspNetCore.Server.Kestrel.KestrelServer.Start[TContext](IHttpApplication`1 application)
---> (Inner Exception #0) Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvException: Error -4090 EADDRNOTAVAIL address not available
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.ThrowError(Int32 statusCode)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.tcp_bind(UvTcpHandle handle, SockAddr& addr, Int32 flags)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvTcpHandle.Bind(ServerAddress address)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.TcpListenerPrimary.CreateListenSocket()
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Listener.<StartAsync>b__8_0(Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.ListenerPrimary.<StartAsync>d__12.MoveNext()<---

2017-06-27 17:08:22.738 +08:00 [Information] "Host","20022","e:\picsig","e:\piclog","e:\pic"------------------------------------
2017-06-27 17:08:23.605 +08:00 [Fatal] Unable to start Kestrel.
System.AggregateException: One or more errors occurred. (Error -4090 EADDRNOTAVAIL address not available) ---> Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvException: Error -4090 EADDRNOTAVAIL address not available
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.ThrowError(Int32 statusCode)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.tcp_bind(UvTcpHandle handle, SockAddr& addr, Int32 flags)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvTcpHandle.Bind(ServerAddress address)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.TcpListenerPrimary.CreateListenSocket()
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Listener.<StartAsync>b__8_0(Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.ListenerPrimary.<StartAsync>d__12.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.KestrelEngine.CreateServer(ServerAddress address)
   at Microsoft.AspNetCore.Server.Kestrel.KestrelServer.Start[TContext](IHttpApplication`1 application)
---> (Inner Exception #0) Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvException: Error -4090 EADDRNOTAVAIL address not available
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.ThrowError(Int32 statusCode)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.tcp_bind(UvTcpHandle handle, SockAddr& addr, Int32 flags)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvTcpHandle.Bind(ServerAddress address)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.TcpListenerPrimary.CreateListenSocket()
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Listener.<StartAsync>b__8_0(Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.ListenerPrimary.<StartAsync>d__12.MoveNext()<---

2017-06-27 17:08:40.338 +08:00 [Information] "Host","20022","e:\picsig","e:\piclog","e:\pic"------------------------------------
2017-06-27 17:08:42.387 +08:00 [Information] Request starting HTTP/1.1 GET http://localhost:5000/  
2017-06-27 17:08:42.818 +08:00 [Information] Request finished in 458.8649ms 404 
2017-06-27 17:08:42.867 +08:00 [Information] Request starting HTTP/1.1 GET http://localhost:5000/  
2017-06-27 17:08:42.872 +08:00 [Information] Request finished in 4.6541ms 404 
2017-06-27 17:09:02.248 +08:00 [Information] Request starting HTTP/1.1 POST http://localhost:5000/InspectPostStudyStatus application/json 104
2017-06-27 17:09:02.736 +08:00 [Information] Executing action method "study.Controllers.InspectController.InspectPostStudyStatus (study)" with arguments (["study.StudyStatusRequest"]) - ModelState is Valid
2017-06-27 17:09:02.821 +08:00 [Information] InspectPostStudyStatus,input 170888="{\"Token\":\"c0a1f99ff2c74a339f8c4fd3594ae80d\",\"Identity\":\"stat\",\"CourseTitle\":\"rec\",\"StartTime\":0,\"EndTime\":0,\"Pictures\":null}",from ip="::1"
2017-06-27 17:09:02.823 +08:00 [Error] InspectPostStudyStatus,"无效的 token！",token="c0a1f99ff2c74a339f8c4fd3594ae80d"
2017-06-27 17:09:02.851 +08:00 [Information] Executing ObjectResult, writing value "Microsoft.AspNetCore.Mvc.ControllerContext".
2017-06-27 17:09:02.906 +08:00 [Information] Executed action "study.Controllers.InspectController.InspectPostStudyStatus (study)" in 585.8202ms
2017-06-27 17:09:02.912 +08:00 [Information] Request finished in 665.3633ms 200 application/json; charset=utf-8
2017-06-27 17:09:58.051 +08:00 [Information] Request starting HTTP/1.1 POST http://localhost:5000/InspectPostStudyStatus application/json 104
2017-06-27 17:09:58.080 +08:00 [Information] Executing action method "study.Controllers.InspectController.InspectPostStudyStatus (study)" with arguments (["study.StudyStatusRequest"]) - ModelState is Valid
2017-06-27 17:09:58.082 +08:00 [Information] InspectPostStudyStatus,input 170888="{\"Token\":\"bd4b8bfe3f1e4c238037b7ee64b6ce38\",\"Identity\":\"stat\",\"CourseTitle\":\"rec\",\"StartTime\":0,\"EndTime\":0,\"Pictures\":null}",from ip="::1"
2017-06-27 17:09:58.082 +08:00 [Error] InspectPostStudyStatus,"无效的 token！",token="bd4b8bfe3f1e4c238037b7ee64b6ce38"
2017-06-27 17:09:58.084 +08:00 [Information] Executing ObjectResult, writing value "Microsoft.AspNetCore.Mvc.ControllerContext".
2017-06-27 17:09:58.087 +08:00 [Information] Executed action "study.Controllers.InspectController.InspectPostStudyStatus (study)" in 8.8832ms
2017-06-27 17:09:58.090 +08:00 [Information] Request finished in 39.2131ms 200 application/json; charset=utf-8
2017-06-27 17:10:21.782 +08:00 [Information] Request starting HTTP/1.1 POST http://localhost:5000/LoginAndQuery application/json 130
2017-06-27 17:10:21.803 +08:00 [Information] Executing action method "study.Controllers.InspectController.LoginAndQuery (study)" with arguments (["study.LoginAndQueryRequest"]) - ModelState is Valid
2017-06-27 17:10:21.811 +08:00 [Information] LoginAndQuery,input="{\"Identity\":\"370686199102070710\",\"Name\":\"rec\",\"DrivingLicenseType\":0,\"Phone\":null,\"Wechat\":null}",from "::1"
2017-06-27 17:10:23.460 +08:00 [Information] Executing ObjectResult, writing value "Microsoft.AspNetCore.Mvc.ControllerContext".
2017-06-27 17:10:23.479 +08:00 [Information] Executed action "study.Controllers.InspectController.LoginAndQuery (study)" in 1691.6406ms
2017-06-27 17:10:23.482 +08:00 [Information] Request finished in 1700.0908ms 200 application/json; charset=utf-8
2017-06-27 17:10:32.900 +08:00 [Information] Request starting HTTP/1.1 POST http://localhost:5000/InspectPostStudyStatus application/json 104
2017-06-27 17:10:32.905 +08:00 [Information] Executing action method "study.Controllers.InspectController.InspectPostStudyStatus (study)" with arguments (["study.StudyStatusRequest"]) - ModelState is Valid
2017-06-27 17:10:32.909 +08:00 [Information] InspectPostStudyStatus,input 170888="{\"Token\":\"31ecce1b9ca9447882e48499c5d19baa\",\"Identity\":\"stat\",\"CourseTitle\":\"rec\",\"StartTime\":0,\"EndTime\":0,\"Pictures\":null}",from ip="::1"
2017-06-27 17:10:33.096 +08:00 [Information] Executing ObjectResult, writing value "Microsoft.AspNetCore.Mvc.ControllerContext".
2017-06-27 17:10:33.099 +08:00 [Information] Executed action "study.Controllers.InspectController.InspectPostStudyStatus (study)" in 193.6572ms
2017-06-27 17:10:33.101 +08:00 [Information] Request finished in 200.8915ms 200 application/json; charset=utf-8
2017-06-27 17:11:09.756 +08:00 [Information] Request starting HTTP/1.1 POST http://localhost:5000/InspectPostStudyStatus application/json 127
2017-06-27 17:11:09.765 +08:00 [Information] Executing action method "study.Controllers.InspectController.InspectPostStudyStatus (study)" with arguments (["study.StudyStatusRequest"]) - ModelState is Valid
2017-06-27 17:11:09.769 +08:00 [Information] InspectPostStudyStatus,input 170888="{\"Token\":\"31ecce1b9ca9447882e48499c5d19baa\",\"Identity\":\"stat\",\"CourseTitle\":\"rec\",\"StartTime\":748723478,\"EndTime\":0,\"Pictures\":null}",from ip="::1"
2017-06-27 17:11:09.886 +08:00 [Information] Executing ObjectResult, writing value "Microsoft.AspNetCore.Mvc.ControllerContext".
2017-06-27 17:11:09.892 +08:00 [Information] Executed action "study.Controllers.InspectController.InspectPostStudyStatus (study)" in 130.7627ms
2017-06-27 17:11:09.898 +08:00 [Information] Request finished in 141.6465ms 200 application/json; charset=utf-8
2017-06-27 17:11:28.120 +08:00 [Information] Request starting HTTP/1.1 POST http://localhost:5000/InspectPostStudyStatus application/json 147
2017-06-27 17:11:28.126 +08:00 [Information] Executing action method "study.Controllers.InspectController.InspectPostStudyStatus (study)" with arguments (["study.StudyStatusRequest"]) - ModelState is Valid
2017-06-27 17:11:28.129 +08:00 [Information] InspectPostStudyStatus,input 170888="{\"Token\":\"31ecce1b9ca9447882e48499c5d19baa\",\"Identity\":\"stat\",\"CourseTitle\":\"rec\",\"StartTime\":748723478,\"EndTime\":2323232,\"Pictures\":null}",from ip="::1"
2017-06-27 17:11:28.222 +08:00 [Information] Executing ObjectResult, writing value "Microsoft.AspNetCore.Mvc.ControllerContext".
2017-06-27 17:11:28.225 +08:00 [Information] Executed action "study.Controllers.InspectController.InspectPostStudyStatus (study)" in 99.9598ms
2017-06-27 17:11:28.228 +08:00 [Information] Request finished in 107.6489ms 200 application/json; charset=utf-8
2017-06-27 17:12:26.309 +08:00 [Information] "Host","20022","e:\picsig","e:\piclog","e:\pic"------------------------------------
2017-06-27 17:12:27.357 +08:00 [Fatal] Unable to start Kestrel.
System.AggregateException: One or more errors occurred. (Error -4090 EADDRNOTAVAIL address not available) ---> Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvException: Error -4090 EADDRNOTAVAIL address not available
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.ThrowError(Int32 statusCode)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.tcp_bind(UvTcpHandle handle, SockAddr& addr, Int32 flags)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvTcpHandle.Bind(ServerAddress address)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.TcpListenerPrimary.CreateListenSocket()
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Listener.<StartAsync>b__8_0(Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.ListenerPrimary.<StartAsync>d__12.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.KestrelEngine.CreateServer(ServerAddress address)
   at Microsoft.AspNetCore.Server.Kestrel.KestrelServer.Start[TContext](IHttpApplication`1 application)
---> (Inner Exception #0) Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvException: Error -4090 EADDRNOTAVAIL address not available
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.ThrowError(Int32 statusCode)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.tcp_bind(UvTcpHandle handle, SockAddr& addr, Int32 flags)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvTcpHandle.Bind(ServerAddress address)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.TcpListenerPrimary.CreateListenSocket()
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Listener.<StartAsync>b__8_0(Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.ListenerPrimary.<StartAsync>d__12.MoveNext()<---

2017-06-27 17:31:51.082 +08:00 [Information] "Host","20022","e:\picsig","e:\piclog","e:\pic"------------------------------------
2017-06-27 17:31:53.507 +08:00 [Information] Request starting HTTP/1.1 GET http://localhost:5000/  
2017-06-27 17:31:53.931 +08:00 [Information] Request finished in 443.246ms 404 
2017-06-27 17:31:53.968 +08:00 [Information] Request starting HTTP/1.1 GET http://localhost:5000/  
2017-06-27 17:31:53.977 +08:00 [Information] Request finished in 9.4263ms 404 
2017-06-27 17:33:00.024 +08:00 [Information] "Host","20022","e:\picsig","e:\piclog","e:\pic"------------------------------------
2017-06-27 17:33:01.031 +08:00 [Fatal] Unable to start Kestrel.
System.AggregateException: One or more errors occurred. (Error -4090 EADDRNOTAVAIL address not available) ---> Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvException: Error -4090 EADDRNOTAVAIL address not available
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.ThrowError(Int32 statusCode)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.tcp_bind(UvTcpHandle handle, SockAddr& addr, Int32 flags)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvTcpHandle.Bind(ServerAddress address)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.TcpListenerPrimary.CreateListenSocket()
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Listener.<StartAsync>b__8_0(Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.ListenerPrimary.<StartAsync>d__12.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.KestrelEngine.CreateServer(ServerAddress address)
   at Microsoft.AspNetCore.Server.Kestrel.KestrelServer.Start[TContext](IHttpApplication`1 application)
---> (Inner Exception #0) Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvException: Error -4090 EADDRNOTAVAIL address not available
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.ThrowError(Int32 statusCode)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.tcp_bind(UvTcpHandle handle, SockAddr& addr, Int32 flags)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvTcpHandle.Bind(ServerAddress address)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.TcpListenerPrimary.CreateListenSocket()
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Listener.<StartAsync>b__8_0(Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.ListenerPrimary.<StartAsync>d__12.MoveNext()<---

